# Generated by Django 4.2.4 on 2025-10-03 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealership_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='dealer_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
