apiVersion: apps/v1
kind: Deployment
metadata:
  name: dealership-api
  labels:
    app: dealership-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dealership-api
  template:
    metadata:
      labels:
        app: dealership-api
    spec:
      initContainers:
        - name: fix-permissions
          image: busybox
          command: ["sh", "-c", "chown -R 1000:1000 /data"]
          volumeMounts:
            - name: sqlite-storage
              mountPath: /data
      containers:
        - name: dealership-api
          image: docker.io/sebetancurch98/dealership-api:1.0.6
          ports:
            - containerPort: 8000
              name: http
          envFrom:
            - configMapRef:
                name: dealership-api-config
          volumeMounts:
            - name: sqlite-storage
              mountPath: /data
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"
      volumes:
        - name: sqlite-storage
          # persistentVolumeClaim:
          #   claimName: sqlite-pvc
          emptyDir: {}
