apiVersion: apps/v1
kind: Deployment
metadata:
  name: dealership-api
  labels:
    app: dealership-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dealership-api
  template:
    metadata:
      labels:
        app: dealership-api
    spec:
      containers:
        - name: dealership-api
          image: sebetancurch98/dealership-api:1.0.0
          ports:
            - containerPort: 8000
              name: http
          envFrom:
            - configMapRef:
                name: dealership-api-config
          volumeMounts:
            - name: sqlite-storage
              mountPath: /data
          resources:
            requests:
              memory: "32Mi"
              cpu: "10m"
            limits:
              memory: "64Mi"
              cpu: "100m"
      volumes:
        - name: sqlite-storage
          emptyDir: {}
