apiVersion: apps/v1
kind: Deployment
metadata:
  name: dealership-api
  labels:
    app: dealership-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dealership-api
  template:
    metadata:
      labels:
        app: dealership-api
    spec:
      containers:
        - name: dealership-api
          image: dealership-app/dealership_api:1.0.0
          ports:
            - containerPort: 8000
              name: http
          envFrom:
            - configMapRef:
                name: dealership-api-config
          volumeMounts:
            - name: sqlite-storage
              mountPath: /data
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - name: sqlite-storage
          persistentVolumeClaim:
            claimName: sqlite-pvc
