apiVersion: v1
kind: Service
metadata:
  name: dealership-api
  labels:
    app: dealership-api
spec:
  type: ClusterIP
  selector:
    app: dealership-api
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
