apiVersion: v1
kind: Service
metadata:
  name: mongo-db
  labels:
    app: mongo-db
spec:
  type: ClusterIP
  selector:
    app: mongo-db
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
      name: mongodb
